AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for Amazon EKS Cluster

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EKSClusterRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

Outputs:
  EKSClusterRoleARN:
    Description: ARN of the EKS Cluster Role
    Value: !GetAtt EKSClusterRole.Arn